// Taglish UI strings. One file, no i18n framework (BLUEPRINT §D).

export const S = {
  appName: 'TindaBot',
  tagline: 'Smart listahan para sa tindahan mo',
  tabs: { bahay: 'Bahay', paninda: 'Paninda', listahan: 'Listahan', ibaPa: 'Iba pa' },
  fab: { bumili: 'Bumili', bilang: 'Bilang', utang: 'Utang', bayad: 'Bayad', gastos: 'Gastos', pera: 'Pera' },

  onboarding: {
    welcome: 'Maligayang pagdating!',
    intro: 'Sasabihin ni TindaBot kung ano ang bibilhin mo, ilan, kailan, at magkano ang dadalhin — base sa bili at bilang mo.',
    storeName: 'Pangalan ng tindahan',
    storeNamePh: 'hal. Tindahan ni Aling Nena',
    restockQ: 'Kailan ka karaniwang namimili ng paninda?',
    restockHint: 'Piliin ang mga araw. Kung wala, piliin ang "Kapag kailangan".',
    whenNeeded: 'Kapag kailangan',
    addProducts: 'Idagdag ang mga paninda mo',
    addHint: 'Piliin ang mga mabilis maubos — mga 10 hanggang 30 items. Pwede kang magdagdag anumang oras.',
    next: 'Susunod',
    finish: 'Tapos na',
    skip: 'Laktawan',
  },

  bahay: {
    title: 'Bilihin',
    trip: 'Biyahe',
    goingToday: 'Pupunta ako ngayon',
    cancelGoingToday: 'Hindi na ngayon',
    share: 'I-share',
    total: 'Dalhin',
    unknownCost: (n: number) => `${n} item ang walang presyo`,
    bilhinNa: 'Bilhin na',
    bilhin: 'Bilhin',
    wagMuna: 'Wag muna',
    empty: 'Wala pang paninda',
    emptyHint: 'Idagdag ang mga paninda mo para masimulan.',
    emptyAdd: 'Idagdag ang paninda',
    nothingToBuy: 'Walang kailangang bilhin ngayon.',
    nothingHint: 'I-record ang bili mo o bilangin ang natira para may masabi si TindaBot.',
    nudge: (names: string) => `Bilangin: ${names}`,
    paydaySoon: (day: string) => `Kinsenas/katapusan ${day} — karaniwang mas maraming bumibili.`,
    bilanginMuna: 'Bilangin muna →',
    bakit: 'Bakit?',
    tantiya: 'tantiya',
    uptoPacks: (n: number, label: string) => `hanggang ${n} ${label}`,
    budget: 'Dala ko ₱',
    budgetHint: 'Pera na dala mo sa biyahe. Hindi kasama ang utang.',
    budgetPacks: (n: number, label: string) => `sa budget: ${n} ${label} muna`,
    kulang: (peso: string) => `Kulang ${peso} para sa buong listahan.`,
    sapat: 'Sapat ang dala mo sa buong listahan.',
  },

  paninda: {
    title: 'Paninda',
    add: 'Idagdag',
    search: 'Hanapin ang paninda…',
    natira: 'natira',
    unknown: '?',
    lastCount: 'huling bilang',
    noData: 'Wala pang data',
    slow: 'Mabagal — wag munang bumili.',
    dead: 'Hindi gumagalaw — isipin kung ititigil.',
    dormant: 'Matagal nang hindi nabibili — nagbebenta ka pa ba?',
    unclear: 'Hindi pa malinaw ang pattern ng bili mo.',
    rebuy: 'karaniwang bili ulit',
    okDays: (d: number) => `ok pa ng ~${d} araw`,
    detail: 'Detalye',
    edit: 'I-edit',
    nasira: 'Nasira / expired',
    itigil: 'Itigil',
    ibalikSaListahan: 'Ibalik sa listahan',
    timeline: 'History',
    burahin: 'Burahin',
    binura: 'Binura',
    ibalik: 'Ibalik',
    packSize: 'Ilan sa isang',
    sellPrice: 'Presyo ng benta (bawat isa)',
    optional: 'opsyonal',
    natiraQ: 'Ilan ang natira ngayon?',
    unitLabel: 'Tawag sa isang piraso',
    packLabel: 'Tawag sa isang balot',
    customName: 'Iba pa — i-type ang pangalan',
    save: 'I-save',
    cancel: 'Kanselahin',
  },

  bumili: {
    title: 'Bumili',
    kanina: 'Kanina',
    product: 'Anong paninda?',
    qty: 'Ilan ang binili?',
    byPack: (label: string) => label,
    byUnit: (label: string) => label,
    totalCost: 'Magkano lahat (₱)?',
    totalHint: 'Pwedeng blangko. Ginagamit para sa tantiyang tubo.',
    natira: 'Ilan ang natira BAGO mo idagdag ang bagong bili?',
    natiraHint: 'Opsyonal, pero ito ang pinakamahalagang bilang. Huwag isama ang bagong bili.',
    when: 'Kailan mo binili?',
    ngayon: 'Ngayon',
    kahapon: 'Kahapon',
    ibangAraw: 'Ibang araw',
    confirm: (natira: number, bought: number, total: number, unit: string) => `Natira ${natira} + bagong bili ${bought} = ${total} ${unit} ngayon`,
    lugi: (cost: string, sell: string) => `${cost} bawat isa? Mas mataas pa sa presyo ng benta (${sell}). Tama ba ang presyo?`,
    highCost: (cost: string) => `${cost} bawat isa? Mukhang mataas. Tama ba ang presyo?`,
    saveAdd: 'I-save at isa pa',
    save: 'I-save',
  },

  bilang: {
    title: 'Bilang',
    hint: 'Bilangin pati nasa kahon. Pwede kang tumigil anumang oras.',
    laktawan: 'Laktawan',
    susunod: 'Susunod',
    tapos: 'Tapos',
    packsPlus: (packLabel: string) => `${packLabel} + piraso`,
    done: (n: number) => `${n} paninda ang nabilang.`,
    nothing: 'Walang kailangang bilangin ngayon.',
    lastCount: (d: number) => (d === 0 ? 'nabilang ngayon' : `huling bilang ${d} araw na`),
  },

  bakit: {
    title: 'Bakit?',
    natira: 'Natira (tantiya)',
    lastCount: 'Huling bilang',
    rate: 'Bilis ng pagkaubos',
    throughput: 'Naubos mo',
    perDay: 'kada araw',
    daysLeft: 'Aabot pa ng',
    need: 'Kailangan hanggang susunod na biyahe',
    tubo: 'Tubo bawat isa',
    cost: 'Puhunan bawat isa (huling bili)',
    confidence: { none: 'Wala pang data', low: 'Tantiya — kaunti pa ang data', mid: 'Medyo tumpak', high: 'Tumpak' },
  },

  ibaPa: {
    title: 'Iba pa',
    settings: 'Settings',
    storeName: 'Pangalan ng tindahan',
    restockDays: 'Araw ng pamimili',
    export: 'I-export (backup)',
    exportHint: 'I-save o i-share ang listahan mo bilang file. Gawin ito buwan-buwan.',
    import: 'I-import',
    importHint: 'Ibalik ang listahan mula sa backup file.',
    importReplaceQ: 'Ibang tindahan ang nasa file. Palitan ang tindahan sa phone na ito?',
    imported: (n: number) => `Na-import: ${n} bagong entry.`,
    demo: 'Subukan ang demo',
    demoHint: 'Palitan ang laman ng sample na tindahan (para lang sa pagsubok).',
    advanced: 'Advanced',
    payday: 'Dagdag benta tuwing kinsenas/katapusan',
    friSat: 'Dagdag benta tuwing Biyernes/Sabado',
    about: 'Tungkol',
    aboutText: 'Lahat ng data ay nasa phone mo lang. Walang internet na kailangan.',
    backupNudge: 'Matagal nang walang backup — i-export ang listahan mo.',
    persisted: (ok: boolean) => (ok ? 'Naka-secure ang storage ng phone para sa app.' : 'Hindi pa ginagarantiya ng phone ang storage — mag-export ng backup buwan-buwan. Nakakatulong ang pag-install sa home screen.'),
  },

  // ---------- P2 ----------
  pera: {
    utang: { title: 'Utang', amount: 'Magkano ang inutang?', note: 'Ano ang inutang? (opsyonal)', save: 'I-save ang utang' },
    bayad: { title: 'Bayad', amount: 'Magkano ang binayad?', save: 'I-save ang bayad' },
    gastos: { title: 'Gastos', amount: 'Magkano ang gastos?', note: 'Para saan? (opsyonal)', category: 'Uri ng gastos', save: 'I-save ang gastos' },
    pera: { title: 'Bilang ng pera', amount: 'Magkano ang pera sa tindahan ngayon?', hint: 'Bilangin ang cash sa kaha. Wala itong tinatantiya — kung ano ang nabilang mo, iyon ang naitala.', save: 'I-save ang bilang' },
    customer: 'Sino?',
    newCustomer: '+ Bagong customer',
    customerName: 'Pangalan',
    customerPhone: 'Cellphone (opsyonal)',
    searchCustomer: 'Hanapin ang customer…',
    when: 'Kailan?',
    invalidAmount: 'Ilagay ang halaga (mahigit ₱0, hanggang 2 decimal).',
    confirmUtang: (name: string, before: string, add: string, after: string) => `${name}: ${before} + ${add} = ${after}`,
    confirmBayad: (name: string, before: string, pay: string, after: string) => `${name}: ${before} − ${pay} = ${after}`,
    categories: { kuryente: 'Kuryente', tubig: 'Tubig', pamasahe: 'Pamasahe', load: 'Load', renta: 'Renta', iba: 'Iba' } as Record<string, string>,
  },
  listahan: {
    title: 'Listahan ng utang',
    outstanding: 'Kabuuang utang sa iyo',
    empty: 'Wala pang naka-lista.',
    emptyHint: 'I-tap ang + at piliin ang Utang para magsimula.',
    sobra: (peso: string) => `sobra ${peso}`,
    bayadNa: 'bayad na',
    lastBayad: (d: number) => (d === 0 ? 'nagbayad ngayon' : `huling bayad ${d} araw na`),
    lastUtang: (d: number) => (d === 0 ? 'umutang ngayon' : `huling utang ${d} araw na`),
    oldest: (date: string) => `pinakamatagal na utang: ${date}`,
    archived: 'Itinigil na customer',
    itigil: 'Itigil',
    ibalik: 'Ibalik sa listahan',
    edit: 'I-edit',
    history: 'History',
    noData: 'Wala pang utang o bayad.',
  },
  ulat: {
    title: 'Ulat',
    naitala: 'Naitala',
    tantiya: 'Tantiya',
    cashLast: 'Huling bilang ng pera',
    cashNone: 'Wala pang bilang ng pera.',
    utangOutstanding: 'Utang sa iyo',
    bentaWeek: 'Benta kada linggo',
    tuboWeek: 'Tubo kada linggo',
    tantiyaHint: (n: number, skipped: number) => `Tantiya lang — base sa bilis ng pagkaubos ng ${n} paninda na may bilang.${skipped ? ` ${skipped} ang walang presyo o puhunan.` : ''} Hindi kasama ang mga tantiya-lang (purchase pattern) na paninda.`,
    week: 'Linggo',
    thisWeek: 'Ngayong linggo',
    lastWeek: 'Nakaraang linggo',
    weeksAgo: (n: number) => `${n} linggo na`,
    gastos: 'Gastos',
    nabili: 'Nabili (puhunan)',
    utangGiven: 'Pinautang',
    utangReceived: 'Nabayaran',
    cashCount: 'Bilang ng pera',
    outstandingEnd: 'Utang sa iyo (katapusan ng linggo)',
    history: 'History ng gastos at pera',
    noHistory: 'Wala pang gastos o bilang ng pera.',
  },

  days: ['Lin', 'Lun', 'Mar', 'Miy', 'Huw', 'Biy', 'Sab'],
  daysLong: ['Linggo', 'Lunes', 'Martes', 'Miyerkules', 'Huwebes', 'Biyernes', 'Sabado'],
}
