// UI strings. One file, no i18n framework (BLUEPRINT §D): `TL` is the original Taglish wording and
// the default; `EN` mirrors it key for key and is type-checked against `TL`, so a missing or extra
// English key is a compile error. Components read them through `useStrings()` (src/ui/i18n.ts),
// which subscribes to the language in the app store; non-React code uses `strings(lang)`.
//
// Developer/debug text (error details, meta keys, phase names) is never translated and never
// lives here. Domain-generated wording (reasons, hints, dates) lives in domain/templates.ts and
// takes the language explicitly.

import type { Lang } from '../domain'
import type { AiErrorCode } from '../ai/client'
import type { CsvRowError } from '../domain'
import type { CloudErrorCode, SignInErrorKind } from '../sync/api'

export const TL = {
  appName: 'TindaBot',
  tagline: 'Smart listahan para sa tindahan mo',
  tabs: { bahay: 'Bahay', paninda: 'Paninda', listahan: 'Listahan', ibaPa: 'Iba pa' },
  fab: { bumili: 'Bumili', bilang: 'Bilang', utang: 'Utang', bayad: 'Bayad', gastos: 'Gastos', pera: 'Pera', open: 'Ilista', benta: 'Benta', resibo: 'Resibo', isulat: 'Isulat', tanong: 'Tanong' },

  common: {
    close: 'isara',
    change: 'palitan',
    name: 'Pangalan',
    back: '‹ Bumalik',
    show: 'Ipakita',
    hide: 'Itago',
    saved: 'Na-save.',
    exported: 'Na-export.',
    copied: 'Na-copy ang listahan.',
    recorded: 'naitala',
    recordedToast: (what: string) => `Naitala: ${what}`,
    addedToast: (name: string) => `Naidagdag: ${name}`,
    notSaved: 'Hindi na-save. Subukan ulit.',
    days: (n: number) => `${n} araw`,
  },

  lang: { title: 'Wika / Language', tl: 'Taglish', en: 'English' },

  /** Shown when the local database cannot be opened at all — the app has nothing to read or save. */
  storage: {
    title: 'Hindi mabuksan ang listahan',
    body: 'Hindi mabuksan ni TindaBot ang local storage ng browser na pinagtataguan ng listahan mo.',
    check: 'I-allow ang site data at cookies para sa site na ito, at huwag gamitin ang private o incognito browsing.',
    retry: 'Subukan muli',
  },

  /** While the demo is the current store: the way out, to the person's own store. */
  demoExit: {
    note: 'Demo ito.',
    start: 'Simulan ang sariling tindahan →',
    back: (name: string) => `Bumalik sa ${name} →`,
    hint: 'Mananatili ang demo sa phone na ito, pero hindi na ito ang gagamitin.',
  },

  /** The stores on this phone (Iba pa): switch, delete, add. */
  stores: {
    title: 'Mga tindahan',
    current: 'Ginagamit',
    use: 'Gamitin',
    delete: 'Burahin',
    add: '＋ Bagong tindahan',
    deleteQ: (name: string) =>
      `Burahin ang "${name}"? Mabubura sa phone na ito ang lahat ng paninda, suki, utang at listahan nito, at hindi na ito lalabas sa cloud backup mo. Hindi na ito maibabalik — mag-export muna kung gusto mo ng kopya.`,
    deleted: (name: string) => `Nabura ang "${name}".`,
    back: (name: string) => `← Bumalik sa ${name}`,
    shared: 'kasama',
    leaveQ: (name: string) =>
      `Umalis sa "${name}"? Mabubura ito sa phone na ito at hindi ka na makakapasok hangga't hindi ka iniimbita ulit. Mananatili sa may-ari ang tindahan at lahat ng naitala.`,
  },

  onboarding: {
    welcome: 'Maligayang pagdating!',
    intro: 'Sasabihin ni TindaBot kung ano ang bibilhin mo, ilan, kailan, at magkano ang dadalhin — base sa bili at bilang mo.',
    storeName: 'Pangalan ng tindahan',
    storeNamePh: 'hal. Tindahan ni Aling Nena',
    defaultStoreName: 'Tindahan ko',
    restockQ: 'Kailan ka karaniwang namimili ng paninda?',
    restockHint: 'Piliin ang mga araw. Kung wala, piliin ang "Kapag kailangan".',
    whenNeeded: 'Kapag kailangan',
    addProducts: 'Idagdag ang mga paninda mo',
    addHint: 'Piliin ang mga mabilis maubos — mga 10 hanggang 30 items. Pwede kang magdagdag anumang oras.',
    next: 'Susunod',
    finish: 'Tapos na',
    skip: 'Laktawan',
  },

  bahay: {
    title: 'Bilihin',
    trip: 'Biyahe',
    today: 'Ngayon',
    goingToday: 'Pupunta ako ngayon',
    cancelGoingToday: 'Hindi na ngayon',
    share: 'I-share',
    shareBring: 'Dalhin',
    total: 'Dalhin',
    unknownCost: (n: number) => `${n} item ang walang presyo`,
    bilhinNa: 'Bilhin na',
    bilhin: 'Bilhin',
    wagMuna: 'Wag muna',
    empty: 'Wala pang paninda',
    emptyHint: 'Idagdag ang mga paninda mo para masimulan.',
    emptyAdd: 'Idagdag ang paninda',
    nothingToBuy: 'Walang kailangang bilhin ngayon.',
    nothingHint: 'I-record ang bili mo o bilangin ang natira para may masabi si TindaBot.',
    nudge: (names: string) => `Bilangin: ${names}`,
    paydaySoon: (day: string) => `Kinsenas/katapusan ${day} — karaniwang mas maraming bumibili.`,
    bilanginMuna: 'Bilangin muna →',
    bakit: 'Bakit?',
    tantiya: 'tantiya',
    uptoPacks: (n: number, label: string) => `hanggang ${n} ${label}`,
    budget: 'Dala ko ₱',
    budgetHint: 'Pera na dala mo sa biyahe. Hindi kasama ang utang.',
    budgetPacks: (n: number, label: string) => `sa budget: ${n} ${label} muna`,
    kulang: (peso: string) => `Kulang ${peso} para sa buong listahan.`,
    sapat: 'Sapat ang dala mo sa buong listahan.',
  },

  paninda: {
    title: 'Paninda',
    add: 'Idagdag',
    search: 'Hanapin ang paninda…',
    natira: 'natira',
    unknown: '?',
    lastCount: 'huling bilang',
    noData: 'Wala pang data',
    slow: 'Mabagal — wag munang bumili.',
    dead: 'Hindi gumagalaw — isipin kung ititigil.',
    dormant: 'Matagal nang hindi nabibili — nagbebenta ka pa ba?',
    unclear: 'Hindi pa malinaw ang pattern ng bili mo.',
    rebuy: 'karaniwang bili ulit',
    rebuyWhen: (when: string) => `karaniwang bili ulit: mga ${when}`,
    okDays: (d: number) => `ok pa ng ~${d} araw`,
    daysLeftShort: (d: string) => `~${d} araw pa`,
    detail: 'Detalye',
    edit: 'I-edit',
    nasira: 'Nasira / expired',
    nasiraSaved: 'Naitala ang nasira.',
    nasiraQty: (unit: string) => `Ilan ang nasira / expired? (${unit})`,
    itigil: 'Itigil',
    ibalikSaListahan: 'Ibalik sa listahan',
    timeline: 'History',
    burahin: 'Burahin',
    binura: 'Binura',
    ibalik: 'Ibalik',
    packSize: 'Ilan sa isang',
    sellPrice: 'Presyo ng benta (bawat isa)',
    optional: 'opsyonal',
    natiraQ: 'Ilan ang natira ngayon?',
    unitLabel: 'Tawag sa isang piraso',
    packLabel: 'Tawag sa isang balot',
    customName: 'Iba pa — i-type ang pangalan',
    save: 'I-save',
    cancel: 'Kanselahin',
    status: 'Status',
    pack: 'Balot',
    price: 'Presyo',
    activeTab: '‹ Aktibo',
    archivedTab: 'Itinigil na paninda ›',
    adjustReason: { sira: 'Nasira', expired: 'Expired', personal: 'Ginamit', iba: 'Iba' } as Record<string, string>,
    histPurchase: (qty: number, unit: string) => `Bumili ${qty} ${unit}`,
    histCount: (qty: number, unit: string) => `Bilang: ${qty} ${unit}`,
    all: 'Lahat',
    inList: 'nasa listahan',
    histSale: (qty: number, unit: string) => `Benta (tally): ${qty} ${unit}`,
    supplierPrices: 'Presyo sa supplier (huling bili)',
    perUnit: (cost: string, unit: string) => `${cost} bawat ${unit}`,
  },

  bumili: {
    title: 'Bumili',
    kanina: 'Kanina',
    product: 'Anong paninda?',
    qty: 'Ilan ang binili?',
    byPack: (label: string) => label,
    byUnit: (label: string) => label,
    totalCost: 'Magkano lahat (₱)?',
    totalHint: 'Pwedeng blangko. Ginagamit para sa tantiyang tubo.',
    natira: 'Ilan ang natira BAGO mo idagdag ang bagong bili?',
    natiraHint: 'Opsyonal, pero ito ang pinakamahalagang bilang. Huwag isama ang bagong bili.',
    when: 'Kailan mo binili?',
    ngayon: 'Ngayon',
    kahapon: 'Kahapon',
    ibangAraw: 'Ibang araw',
    confirm: (natira: number, bought: number, total: number, unit: string) => `Natira ${natira} + bagong bili ${bought} = ${total} ${unit} ngayon`,
    lugi: (cost: string, sell: string) => `${cost} bawat isa? Mas mataas pa sa presyo ng benta (${sell}). Tama ba ang presyo?`,
    highCost: (cost: string) => `${cost} bawat isa? Mukhang mataas. Tama ba ang presyo?`,
    saveAdd: 'I-save at isa pa',
    save: 'I-save',
    supplier: 'Saan binili? (supplier)',
    supplierHint: 'Opsyonal. Naaalala ang presyo bawat supplier.',
    lastAt: (supplier: string, cost: string) => `Huling presyo sa ${supplier}: ${cost} bawat isa`,
  },

  bilang: {
    title: 'Bilang',
    hint: 'Bilangin pati nasa kahon. Pwede kang tumigil anumang oras.',
    laktawan: 'Laktawan',
    susunod: 'Susunod',
    tapos: 'Tapos',
    packsPlus: (packLabel: string) => `${packLabel} + piraso`,
    done: (n: number) => `${n} paninda ang nabilang.`,
    nothing: 'Walang kailangang bilangin ngayon.',
    lastCount: (d: number) => (d === 0 ? 'nabilang ngayon' : `huling bilang ${d} araw na`),
  },

  bakit: {
    title: 'Bakit?',
    natira: 'Natira (tantiya)',
    lastCount: 'Huling bilang',
    rate: 'Bilis ng pagkaubos',
    throughput: 'Naubos mo',
    perDay: 'kada araw',
    daysLeft: 'Aabot pa ng',
    need: 'Kailangan hanggang susunod na biyahe',
    tubo: 'Tubo bawat isa',
    cost: 'Puhunan bawat isa (huling bili)',
    tantiya: 'Tantiya',
    lastCountAgo: (d: number, qty: string, unit: string) => `${d} araw na (${qty} ${unit})`,
    throughputIn: (units: string, unit: string, d: string) => `~${units} ${unit} sa ~${d} araw`,
    confidence: { none: 'Wala pang data', low: 'Tantiya — kaunti pa ang data', mid: 'Medyo tumpak', high: 'Tumpak' },
    flagInconsistent: 'Hindi tugma ang huling bilang sa dalas ng bili — tama ba? Baka naisama ang bagong bili sa bilang.',
    flagMissingPurchase: 'Mukhang may hindi na-record na bili. Idagdag ito sa Bumili at piliin ang tamang araw.',
    flagLugi: 'Mas mataas ang puhunan kaysa presyo ng benta. Tama ba ang presyo?',
    tallied: 'Naitalang benta mula sa huling bilang',
    talliedNote: 'Kapag mas marami ang naitalang benta kaysa sa tantiya, ito ang ginagamit.',
  },

  ibaPa: {
    title: 'Iba pa',
    settings: 'Settings',
    storeName: 'Pangalan ng tindahan',
    restockDays: 'Araw ng pamimili',
    backup: 'Backup',
    export: 'I-export (backup)',
    exportHint: 'I-save ang listahan bilang file. Buwan-buwan sana.',
    import: 'I-import',
    importHint: 'Ibalik ang listahan mula sa backup file.',
    importReplaceQ: 'Ibang tindahan ang nasa file. Palitan ang tindahan sa phone na ito?',
    imported: (n: number) => `Na-import: ${n} bagong entry.`,
    importNotExport: 'Hindi ito TindaBot export file.',
    exportStarted: 'Ipinasa na sa browser — baka tanungin ka pa nito kung saan i-save.',
    exportFailed: 'Hindi na-export ang file.',
    importFailed: 'Hindi na-import ang file.',
    demo: 'Subukan ang demo',
    advanced: 'Advanced',
    payday: 'Dagdag benta tuwing kinsenas/katapusan',
    friSat: 'Dagdag benta tuwing Biyernes/Sabado',
    about: 'Tungkol',
    aboutText: 'Nasa phone mo ang listahan at gumagana kahit walang internet. Opsyonal ang cloud backup — kopya lang ito; nananatili sa phone ang lahat.',
    backupNudge: 'Matagal nang walang backup — i-export ang listahan mo.',
    persisted: (ok: boolean) => (ok ? 'Naka-secure ang storage ng phone para sa app.' : 'Hindi pa garantisado ang storage ng phone — mag-export buwan-buwan.'),
    katulong: 'Katulong (AI)',
    katulongHint: 'Kailangan ng internet at sign-in. Draft lang ang gawa ng AI — ikaw pa rin ang magse-save.',
    memberNote: 'Kasama ka sa tindahan na ito. Ang may-ari lang ang makakapagpalit ng pangalan at araw ng pamimili.',
  },

  // ---------- P2 ----------
  pera: {
    utang: { title: 'Utang', amount: 'Magkano ang inutang?', note: 'Ano ang inutang? (opsyonal)', save: 'I-save ang utang' },
    bayad: { title: 'Bayad', amount: 'Magkano ang binayad?', save: 'I-save ang bayad' },
    gastos: { title: 'Gastos', amount: 'Magkano ang gastos?', note: 'Para saan? (opsyonal)', category: 'Uri ng gastos', save: 'I-save ang gastos' },
    pera: { title: 'Bilang ng pera', amount: 'Magkano ang pera sa tindahan ngayon?', hint: 'Bilangin ang cash sa kaha. Walang tinatantiya dito.', save: 'I-save ang bilang' },
    customer: 'Sino?',
    newCustomer: '+ Bagong customer',
    customerName: 'Pangalan',
    customerPhone: 'Cellphone (opsyonal)',
    searchCustomer: 'Hanapin ang customer…',
    when: 'Kailan?',
    invalidAmount: 'Ilagay ang halaga (mahigit ₱0, hanggang 2 decimal).',
    confirmUtang: (name: string, before: string, add: string, after: string) => `${name}: ${before} + ${add} = ${after}`,
    confirmBayad: (name: string, before: string, pay: string, after: string) => `${name}: ${before} − ${pay} = ${after}`,
    categories: { kuryente: 'Kuryente', tubig: 'Tubig', pamasahe: 'Pamasahe', load: 'Load', renta: 'Renta', iba: 'Iba' } as Record<string, string>,
  },
  listahan: {
    title: 'Listahan ng utang',
    outstanding: 'Kabuuang utang sa iyo',
    empty: 'Wala pang naka-lista.',
    emptyHint: 'I-tap ang + at piliin ang Utang para magsimula.',
    sobra: (peso: string) => `sobra ${peso}`,
    bayadNa: 'bayad na',
    lastBayad: (d: number) => (d === 0 ? 'nagbayad ngayon' : `huling bayad ${d} araw na`),
    lastUtang: (d: number) => (d === 0 ? 'umutang ngayon' : `huling utang ${d} araw na`),
    oldest: (date: string) => `pinakamatagal na utang: ${date}`,
    archived: 'Itinigil na customer',
    mayBalanse: 'may balanse pa',
    itigil: 'Itigil',
    ibalik: 'Ibalik sa listahan',
    edit: 'I-edit',
    history: 'History',
    noData: 'Wala pang utang o bayad.',
    status: 'Status',
    cellphone: 'Cellphone',
    histUtang: (amount: string) => `Utang ${amount}`,
    histBayad: (amount: string) => `Bayad ${amount}`,
  },
  ulat: {
    title: 'Ulat',
    naitala: 'Naitala',
    tantiya: 'Tantiya',
    cashLast: 'Huling bilang ng pera',
    cashNone: 'Wala pang bilang ng pera.',
    utangOutstanding: 'Utang sa iyo',
    bentaWeek: 'Benta kada linggo',
    tuboWeek: 'Tubo kada linggo',
    tantiyaHint: (n: number, skipped: number) => `Tantiya lang — base sa bilis ng pagkaubos ng ${n} paninda na may bilang.${skipped ? ` ${skipped} ang walang presyo o puhunan.` : ''} Hindi kasama ang mga tantiya-lang (purchase pattern) na paninda.`,
    week: 'Linggo',
    thisWeek: 'Ngayong linggo',
    lastWeek: 'Nakaraang linggo',
    weeksAgo: (n: number) => `${n} linggo na`,
    gastos: 'Gastos',
    nabili: 'Nabili (puhunan)',
    utangGiven: 'Pinautang',
    utangReceived: 'Nabayaran',
    cashCount: 'Bilang ng pera',
    outstandingEnd: 'Utang sa iyo (katapusan ng linggo)',
    history: 'History ng gastos at pera',
    noHistory: 'Wala pang gastos o bilang ng pera.',
  },

  // ---------- P3a cloud backup ----------
  cloud: {
    title: 'Cloud backup',
    unavailable: 'Hindi available ang cloud backup sa build na ito. Gumagana pa rin ang lahat sa phone mo.',
    signIn: 'Mag-sign in gamit ang Google',
    signInHint: 'Kopya ng listahan mo sa cloud kung sakaling mawala ang phone. Nasa phone pa rin ang lahat.',
    signInFailed: 'Hindi naka-sign in. Subukan ulit.',
    /** Failed return leg of the Google redirect, by app-level kind (never the provider's text). */
    signInErrors: {
      cancelled: 'Hindi natuloy ang pag-sign in — kinansela o hindi pinayagan sa Google. Subukan ulit.',
      exchange: 'Hindi natapos ang pag-sign in (naiba ang browser o nag-expire). Subukan ulit sa parehong browser.',
      provider: 'Hindi natuloy ang pag-sign in sa Google. Subukan ulit mamaya.',
    } satisfies Record<SignInErrorKind, string>,
    signedInAs: (email: string) => `Naka-sign in: ${email}`,
    syncNow: 'I-sync ngayon',
    signOut: 'Mag-sign out',
    signOutHint: 'Mananatili sa phone ang listahan mo; titigil lang ang backup.',
    status: {
      idle: (ago: string) => `Naka-backup · huling sync ${ago}`,
      idleNever: 'Naka-connect sa cloud.',
      syncing: 'Nagsi-sync…',
      offline: (n: number) => (n ? `Offline — ${n} entry ang hindi pa naka-backup. Masi-sync pag may internet.` : 'Offline — naka-backup na ang lahat.'),
      error: (msg: string) => `Hindi na-sync: ${msg}`,
      unavailable: 'Pansamantalang wala ang cloud backup. Ligtas ang listahan sa phone — masi-sync pag bumalik.',
      unavailablePending: (n: number) => `Pansamantalang wala ang cloud backup. ${n} entry ang naka-antay — ligtas lahat sa phone.`,
      authNeeded: 'Mag-sign in ulit para magpatuloy ang backup. Nasa phone pa rin ang listahan.',
      localOnly: 'Demo — hindi naka-sync sa cloud.',
      unbound: 'Hindi pa naka-connect ang tindahan na ito sa cloud. I-tap ang "I-sync ngayon".',
      pending: (n: number) => `${n} entry ang hindi pa naka-backup`,
    },
    /** Sync failures by app-level category (never raw server text). Shown inside status.error(). */
    errors: {
      network: 'walang koneksyon',
      unavailable: 'pansamantalang wala ang cloud',
      auth: 'kailangan mag-sign in ulit',
      denied: 'hindi pinayagan ng cloud (ibang account?)',
      store_gone: 'hindi na available ang tindahan sa cloud',
      server: 'may problema sa cloud — susubukan ulit',
      unknown: 'may problema — susubukan ulit',
    } satisfies Record<CloudErrorCode, string>,
    ago: { justNow: 'kanina lang', minutes: (n: number) => `${n} min ang nakalipas`, hours: (n: number) => `${n} oras ang nakalipas`, days: (n: number) => `${n} araw ang nakalipas` },
    skew: (min: number) => `Mali yata ang oras ng phone mo (≈ ${min} min ang layo sa server). Ayusin sa Settings ng phone para tama ang pagkakasunod ng mga entry.`,
  },


  // ---------- P4/P5 (decided 2026-10-01) ----------
  /** Tally: tap per sale; additive help for the estimate, never required. */
  tally: {
    title: 'Benta (tally)',
    hint: 'I-tap ang paninda sa bawat benta. Hindi kailangang isama lahat — dagdag-tulong lang ito sa tantiya.',
    count: (n: number) => (n === 1 ? '1 benta' : `${n} benta`),
    minus: 'bawasan',
    save: 'I-save',
    saved: (n: number) => `Naitala ang ${n} benta.`,
    unsavedQ: 'May hindi pa na-save na benta. Isara pa rin?',
  },

  ai: {
    signInFirst: 'Mag-sign in muna sa Iba pa → Cloud backup para magamit ang AI. Gumagana pa rin ang lahat ng iba.',
    errors: {
      signed_out: 'Mag-sign in muna sa Iba pa → Cloud backup.',
      offline: 'Walang internet — kailangan ng internet ang AI. Gumagana pa rin ang lahat ng iba.',
      auth: 'Mag-sign in ulit sa Iba pa → Cloud backup.',
      rate_limited: 'Masyadong marami na ang tanong ngayon — subukan ulit mamaya.',
      busy: 'Abala ang AI ngayon — subukan ulit maya-maya.',
      not_configured: 'Hindi pa naka-setup ang AI sa app na ito.',
      too_large: 'Masyadong malaki ang litrato — subukan ang mas malapit na kuha.',
      failed: 'Hindi nakuha ang sagot — subukan ulit.',
    } satisfies Record<AiErrorCode, string>,
  },

  /** Receipt photo / typed or dictated note → drafts → I-save (/ai/parse). */
  scan: {
    title: 'I-scan ang resibo',
    textTitle: 'Isulat ang naitala',
    take: '📷 Kunan ang resibo',
    choose: '🖼️ Pumili ng litrato',
    imageNote: 'Hindi sine-save ang litrato — binabasa lang, tapos itinatapon.',
    textHint: 'Hal.: "bumili ako ng 2 case Coke 1560 sa Puregold, natira 5 Kopiko". Pwede ring gamitin ang mic ng keyboard.',
    textPlaceholder: 'Isulat dito…',
    mic: '🎤 Magsalita',
    listening: 'Nakikinig…',
    read: 'Basahin',
    reading: 'Binabasa…',
    review: 'Suriin bago i-save',
    none: 'Walang nabasang item.',
    unreadable: 'Hindi mabasa:',
    pick: 'Piliin ang paninda…',
    notInStore: (name: string) => `"${name}" — wala sa paninda mo`,
    kindPurchase: 'Bili',
    kindCount: 'Natira',
    qty: 'Ilan',
    total: '₱ lahat',
    supplier: 'Supplier',
    when: 'Kailan?',
    save: (n: number) => `I-save (${n})`,
    saved: (n: number) => `Naitala ang ${n} entry.`,
    again: 'Ulitin',
  },

  /** "Tanong kay TindaBot" (/ai/chat) with the offline briefing on top. */
  ask: {
    title: 'Tanong kay TindaBot',
    briefing: 'Ngayong araw',
    placeholder: 'Hal.: Ilan pa ang Coke? Magkano ang dadalhin ko?',
    send: 'Itanong',
    thinking: 'Tinitingnan…',
    unverified: 'hindi verified',
    unverifiedText: 'May numero sa sagot na hindi ko ma-verify — tingnan muna sa app.',
    looked: (what: string) => `Tiningnan: ${what}`,
    tools: { get_product: 'paninda', list_events: 'mga naitala', get_shopping_list: 'listahan', get_week_summary: 'Ulat', get_customer: 'suki' } as Record<string, string>,
    examples: ['Ano ang uunahin kong bilhin?', 'Ilan pa ang natira sa pinakamabenta ko?', 'Magkano ang gastos ko ngayong linggo?'],
    note: 'Sumasagot lang mula sa naitala mo. Hindi ito nagse-save o nagbabago ng kahit ano.',
  },

  /** Products from a spreadsheet (CSV). */
  csv: {
    title: 'I-import ang paninda (CSV)',
    hint: 'Mula sa spreadsheet. Mga column: name, category, unit_label, pack_size, pack_label, sell_price, natira. Hindi gagalawin ang mga dati nang paninda.',
    choose: 'Pumili ng CSV file',
    template: 'I-download ang halimbawa',
    noHeader: 'Walang "name" na column sa file — tingnan ang halimbawa.',
    ready: (n: number) => (n === 1 ? '1 bagong paninda' : `${n} bagong paninda`),
    skipped: 'Hindi isasama:',
    exists: 'nasa paninda na',
    line: (n: number) => `Linya ${n}`,
    errors: { no_name: 'walang pangalan', bad_pack_size: 'mali ang pack_size', bad_price: 'mali ang presyo', bad_natira: 'mali ang natira', duplicate: 'ulit sa file' } satisfies Record<CsvRowError['reason'], string>,
    add: (n: number) => `Idagdag (${n})`,
    added: (n: number) => `Naidagdag ang ${n} paninda.`,
    failed: 'Hindi mabasa ang file.',
  },

  /** Household (P5): share a store with another person's account. */
  household: {
    title: 'Kasama sa tindahan',
    hint: 'Ibahagi ang tindahan sa kasama sa bahay. May sarili silang Google account at phone; pareho kayong makakapagtala.',
    signInFirst: 'Mag-sign in muna para makapag-share o makasali.',
    demo: 'Hindi pwedeng i-share ang demo.',
    invite: 'Gumawa ng invite code',
    code: 'Invite code',
    codeHint: (until: string) => `Ibigay ang code. Isang beses lang magagamit, hanggang ${until}.`,
    copy: 'Kopyahin',
    copied: 'Na-copy ang code.',
    join: 'Sumali sa ibang tindahan',
    joinPlaceholder: 'Invite code',
    joinBtn: 'Sumali',
    joined: (name: string) => `Kasama ka na sa ${name}.`,
    joinErrors: { invalid: 'Mali, nagamit na, o expired ang code.', too_many: 'Masyadong maraming maling code — subukan ulit mamaya.', own: 'Code ito ng sarili mong tindahan.' },
    members: 'May access',
    owner: 'may-ari',
    member: 'kasama',
    you: 'ikaw',
    remove: 'Alisin',
    removeQ: (who: string) => `Alisin si ${who}? Hindi na sila makakapasok; mananatili sa tindahan ang lahat ng naitala nila.`,
    removed: 'Naalis.',
    failed: 'Hindi natuloy — subukan ulit.',
    notReady: 'Kailangan munang i-sync ang tindahan sa cloud.',
  },

  days: ['Lin', 'Lun', 'Mar', 'Miy', 'Huw', 'Biy', 'Sab'],
  daysLong: ['Linggo', 'Lunes', 'Martes', 'Miyerkules', 'Huwebes', 'Biyernes', 'Sabado'],
}

/** Shape of `TL` with literal texts widened to `string` (so `EN` may say something else). */
type Widen<T> = T extends string
  ? string
  : T extends (...args: infer A) => infer R
    ? (...args: A) => Widen<R>
    : T extends readonly (infer U)[]
      ? Widen<U>[]
      : T extends object
        ? { [K in keyof T]: Widen<T[K]> }
        : T
export type Strings = Widen<typeof TL>

export const EN: Strings = {
  appName: 'TindaBot',
  tagline: 'The smart listahan for your store',
  tabs: { bahay: 'Home', paninda: 'Products', listahan: 'Utang list', ibaPa: 'More' },
  fab: { bumili: 'Bought', bilang: 'Count', utang: 'Utang', bayad: 'Payment', gastos: 'Expense', pera: 'Cash', open: 'Record', benta: 'Sales', resibo: 'Receipt', isulat: 'Write', tanong: 'Ask' },

  common: {
    close: 'close',
    change: 'change',
    name: 'Name',
    back: '‹ Back',
    show: 'Show',
    hide: 'Hide',
    saved: 'Saved.',
    exported: 'Exported.',
    copied: 'List copied.',
    recorded: 'recorded',
    recordedToast: (what: string) => `Recorded: ${what}`,
    addedToast: (name: string) => `Added: ${name}`,
    notSaved: 'Not saved. Please try again.',
    days: (n: number) => `${n} ${n === 1 ? 'day' : 'days'}`,
  },

  lang: { title: 'Wika / Language', tl: 'Taglish', en: 'English' },

  storage: {
    title: 'Cannot open your listahan',
    body: "TindaBot cannot open the browser's local storage where your listahan is kept.",
    check: 'Allow site data and cookies for this site, and do not use private or incognito browsing.',
    retry: 'Try again',
  },

  demoExit: {
    note: 'This is a demo.',
    start: 'Start my own store →',
    back: (name: string) => `Back to ${name} →`,
    hint: 'The demo stays on this phone, but the app stops using it.',
  },

  stores: {
    title: 'Stores',
    current: 'In use',
    use: 'Use',
    delete: 'Delete',
    add: '＋ New store',
    deleteQ: (name: string) =>
      `Delete "${name}"? All its products, customers, utang and entries are removed from this phone, and it no longer appears in your cloud backup. This cannot be undone — export it first if you want a copy.`,
    deleted: (name: string) => `"${name}" deleted.`,
    back: (name: string) => `← Back to ${name}`,
    shared: 'shared',
    leaveQ: (name: string) =>
      `Leave "${name}"? It is removed from this phone and you lose access until you are invited again. The owner keeps the store and everything recorded.`,
  },

  onboarding: {
    welcome: 'Welcome!',
    intro: 'TindaBot tells you what to buy, how many, when, and how much cash to bring — based on what you bought and counted.',
    storeName: 'Store name',
    storeNamePh: 'e.g. Aling Nena’s Store',
    defaultStoreName: 'My store',
    restockQ: 'When do you usually go buy stock?',
    restockHint: 'Pick the days. If there is no fixed day, choose "When needed".',
    whenNeeded: 'When needed',
    addProducts: 'Add your products',
    addHint: 'Pick the ones that run out fast — about 10 to 30 items. You can add more any time.',
    next: 'Next',
    finish: 'Done',
    skip: 'Skip',
  },

  bahay: {
    title: 'To buy',
    trip: 'Trip',
    today: 'Today',
    goingToday: 'I’m going today',
    cancelGoingToday: 'Not today after all',
    share: 'Share',
    shareBring: 'Bring',
    total: 'Bring',
    unknownCost: (n: number) => `${n} ${n === 1 ? 'item has' : 'items have'} no price`,
    bilhinNa: 'Buy now',
    bilhin: 'Buy',
    wagMuna: 'Not yet',
    empty: 'No products yet',
    emptyHint: 'Add your products to get started.',
    emptyAdd: 'Add a product',
    nothingToBuy: 'Nothing needs buying right now.',
    nothingHint: 'Record what you bought or count what’s left so TindaBot has something to say.',
    nudge: (names: string) => `Count: ${names}`,
    paydaySoon: (day: string) => `Payday ${day} — usually more customers.`,
    bilanginMuna: 'Count first →',
    bakit: 'Why?',
    tantiya: 'estimate',
    uptoPacks: (n: number, label: string) => `up to ${n} ${label}`,
    budget: 'I have ₱',
    budgetHint: 'Cash you are bringing on the trip. Utang not included.',
    budgetPacks: (n: number, label: string) => `within budget: ${n} ${label} for now`,
    kulang: (peso: string) => `${peso} short for the whole list.`,
    sapat: 'You have enough for the whole list.',
  },

  paninda: {
    title: 'Products',
    add: 'Add',
    search: 'Search products…',
    natira: 'left',
    unknown: '?',
    lastCount: 'last count',
    noData: 'No data yet',
    slow: 'Slow — hold off buying.',
    dead: 'Not moving — consider dropping it.',
    dormant: 'Not bought for a long time — do you still sell it?',
    unclear: 'Your buying pattern is not clear yet.',
    rebuy: 'usual re-buy',
    rebuyWhen: (when: string) => `usual re-buy: around ${when}`,
    okDays: (d: number) => `ok for ~${d} more ${d === 1 ? 'day' : 'days'}`,
    daysLeftShort: (d: string) => `~${d} ${d === '1' ? 'day' : 'days'} left`,
    detail: 'Details',
    edit: 'Edit',
    nasira: 'Damaged / expired',
    nasiraSaved: 'Damaged stock recorded.',
    nasiraQty: (unit: string) => `How many were damaged / expired? (${unit})`,
    itigil: 'Stop selling',
    ibalikSaListahan: 'Put back on the list',
    timeline: 'History',
    burahin: 'Delete',
    binura: 'Deleted',
    ibalik: 'Restore',
    packSize: 'How many per',
    sellPrice: 'Selling price (each)',
    optional: 'optional',
    natiraQ: 'How many are left now?',
    unitLabel: 'What one piece is called',
    packLabel: 'What one pack is called',
    customName: 'Other — type the name',
    save: 'Save',
    cancel: 'Cancel',
    status: 'Status',
    pack: 'Pack',
    price: 'Price',
    activeTab: '‹ Active',
    archivedTab: 'Stopped products ›',
    adjustReason: { sira: 'Damaged', expired: 'Expired', personal: 'Used', iba: 'Other' } as Record<string, string>,
    histPurchase: (qty: number, unit: string) => `Bought ${qty} ${unit}`,
    histCount: (qty: number, unit: string) => `Count: ${qty} ${unit}`,
    all: 'All',
    inList: 'on the list',
    histSale: (qty: number, unit: string) => `Sales (tally): ${qty} ${unit}`,
    supplierPrices: 'Supplier prices (last purchase)',
    perUnit: (cost: string, unit: string) => `${cost} per ${unit}`,
  },

  bumili: {
    title: 'Bought',
    kanina: 'Earlier',
    product: 'Which product?',
    qty: 'How many did you buy?',
    byPack: (label: string) => label,
    byUnit: (label: string) => label,
    totalCost: 'Total paid (₱)?',
    totalHint: 'Can be blank. Used for the profit estimate.',
    natira: 'How many were left BEFORE you added the new stock?',
    natiraHint: 'Optional, but this is the most important count. Do not include the new stock.',
    when: 'When did you buy it?',
    ngayon: 'Today',
    kahapon: 'Yesterday',
    ibangAraw: 'Another day',
    confirm: (natira: number, bought: number, total: number, unit: string) => `Left ${natira} + newly bought ${bought} = ${total} ${unit} now`,
    lugi: (cost: string, sell: string) => `${cost} each? That is above the selling price (${sell}). Is the price right?`,
    highCost: (cost: string) => `${cost} each? Looks high. Is the price right?`,
    saveAdd: 'Save and add another',
    save: 'Save',
    supplier: 'Where did you buy? (supplier)',
    supplierHint: 'Optional. Remembers the price per supplier.',
    lastAt: (supplier: string, cost: string) => `Last price at ${supplier}: ${cost} each`,
  },

  bilang: {
    title: 'Count',
    hint: 'Count what’s in the boxes too. You can stop any time.',
    laktawan: 'Skip',
    susunod: 'Next',
    tapos: 'Done',
    packsPlus: (packLabel: string) => `${packLabel} + pieces`,
    done: (n: number) => `${n} ${n === 1 ? 'product' : 'products'} counted.`,
    nothing: 'Nothing needs counting right now.',
    lastCount: (d: number) => (d === 0 ? 'counted today' : `last count ${d} ${d === 1 ? 'day' : 'days'} ago`),
  },

  bakit: {
    title: 'Why?',
    natira: 'Left (estimate)',
    lastCount: 'Last count',
    rate: 'How fast it goes',
    throughput: 'You went through',
    perDay: 'per day',
    daysLeft: 'Will last',
    need: 'Needed until the next trip',
    tubo: 'Profit each',
    cost: 'Cost each (last purchase)',
    tantiya: 'Estimate',
    lastCountAgo: (d: number, qty: string, unit: string) => `${d} ${d === 1 ? 'day' : 'days'} ago (${qty} ${unit})`,
    throughputIn: (units: string, unit: string, d: string) => `~${units} ${unit} in ~${d} days`,
    confidence: { none: 'No data yet', low: 'Estimate — little data so far', mid: 'Fairly accurate', high: 'Accurate' },
    flagInconsistent: 'The last count does not match how often you buy — is it right? The new stock may have been included in the count.',
    flagMissingPurchase: 'Looks like a purchase was not recorded. Add it under Bought and pick the right day.',
    flagLugi: 'Cost is higher than the selling price. Is the price right?',
    tallied: 'Sales tallied since the last count',
    talliedNote: 'When more sales were tallied than estimated, the tally is used.',
  },

  ibaPa: {
    title: 'More',
    settings: 'Settings',
    storeName: 'Store name',
    restockDays: 'Buying days',
    backup: 'Backup',
    export: 'Export (backup)',
    exportHint: 'Save your list as a file. Once a month is enough.',
    import: 'Import',
    importHint: 'Restore the list from a backup file.',
    importReplaceQ: 'The file holds a different store. Replace the store on this phone?',
    imported: (n: number) => `Imported: ${n} new ${n === 1 ? 'entry' : 'entries'}.`,
    importNotExport: 'This is not a TindaBot export file.',
    exportStarted: 'Handed to your browser — it may still ask you where to save it.',
    exportFailed: 'The file could not be exported.',
    importFailed: 'The file could not be imported.',
    demo: 'Try the demo',
    advanced: 'Advanced',
    payday: 'Extra sales on payday (15th/30th)',
    friSat: 'Extra sales on Fridays/Saturdays',
    about: 'About',
    aboutText: 'Your list lives on your phone and works without internet. Cloud backup is optional — it is only a copy; everything stays on the phone.',
    backupNudge: 'No backup for a while — export your list.',
    persisted: (ok: boolean) => (ok ? 'The phone has secured storage for the app.' : 'The phone does not guarantee storage yet — export monthly.'),
    katulong: 'Helper (AI)',
    katulongHint: 'Needs the internet and sign-in. The AI only drafts — you still do the saving.',
    memberNote: 'You share this store. Only the owner can change its name and supplier days.',
  },

  // ---------- P2 ----------
  pera: {
    utang: { title: 'Utang', amount: 'How much was borrowed?', note: 'What was it for? (optional)', save: 'Save utang' },
    bayad: { title: 'Payment', amount: 'How much was paid?', save: 'Save payment' },
    gastos: { title: 'Expense', amount: 'How much was spent?', note: 'What for? (optional)', category: 'Type of expense', save: 'Save expense' },
    pera: { title: 'Cash count', amount: 'How much cash is in the store right now?', hint: 'Count the cash in the drawer. Nothing is estimated here.', save: 'Save count' },
    customer: 'Who?',
    newCustomer: '+ New customer',
    customerName: 'Name',
    customerPhone: 'Cellphone (optional)',
    searchCustomer: 'Search customers…',
    when: 'When?',
    invalidAmount: 'Enter an amount (more than ₱0, up to 2 decimals).',
    confirmUtang: (name: string, before: string, add: string, after: string) => `${name}: ${before} + ${add} = ${after}`,
    confirmBayad: (name: string, before: string, pay: string, after: string) => `${name}: ${before} − ${pay} = ${after}`,
    categories: { kuryente: 'Electricity', tubig: 'Water', pamasahe: 'Fare', load: 'Load', renta: 'Rent', iba: 'Other' } as Record<string, string>,
  },
  listahan: {
    title: 'Utang list',
    outstanding: 'Total owed to you',
    empty: 'Nothing listed yet.',
    emptyHint: 'Tap + and choose Utang to start.',
    sobra: (peso: string) => `${peso} overpaid`,
    bayadNa: 'paid up',
    lastBayad: (d: number) => (d === 0 ? 'paid today' : `last payment ${d} ${d === 1 ? 'day' : 'days'} ago`),
    lastUtang: (d: number) => (d === 0 ? 'borrowed today' : `last utang ${d} ${d === 1 ? 'day' : 'days'} ago`),
    oldest: (date: string) => `oldest unpaid: ${date}`,
    archived: 'Stopped customers',
    mayBalanse: 'still has a balance',
    itigil: 'Stop',
    ibalik: 'Put back on the list',
    edit: 'Edit',
    history: 'History',
    noData: 'No utang or payments yet.',
    status: 'Status',
    cellphone: 'Cellphone',
    histUtang: (amount: string) => `Utang ${amount}`,
    histBayad: (amount: string) => `Payment ${amount}`,
  },
  ulat: {
    title: 'Report',
    naitala: 'Recorded',
    tantiya: 'Estimate',
    cashLast: 'Last cash count',
    cashNone: 'No cash count yet.',
    utangOutstanding: 'Owed to you',
    bentaWeek: 'Sales per week',
    tuboWeek: 'Profit per week',
    tantiyaHint: (n: number, skipped: number) => `Estimate only — based on how fast ${n} counted ${n === 1 ? 'product goes' : 'products go'}.${skipped ? ` ${skipped} ${skipped === 1 ? 'has' : 'have'} no price or cost.` : ''} Estimate-only (purchase pattern) products are not included.`,
    week: 'Week',
    thisWeek: 'This week',
    lastWeek: 'Last week',
    weeksAgo: (n: number) => `${n} ${n === 1 ? 'week' : 'weeks'} ago`,
    gastos: 'Expenses',
    nabili: 'Bought (cost)',
    utangGiven: 'Lent',
    utangReceived: 'Paid back',
    cashCount: 'Cash count',
    outstandingEnd: 'Owed to you (end of week)',
    history: 'Expense and cash history',
    noHistory: 'No expenses or cash counts yet.',
  },

  // ---------- P3a cloud backup ----------
  cloud: {
    title: 'Cloud backup',
    unavailable: 'Cloud backup is not available in this build. Everything still works on your phone.',
    signIn: 'Sign in with Google',
    signInHint: 'Keeps a copy of your list in the cloud in case the phone is lost. Everything stays on the phone.',
    signInFailed: 'Not signed in. Try again.',
    signInErrors: {
      cancelled: 'Sign-in did not go through — cancelled or not allowed at Google. Try again.',
      exchange: 'Sign-in could not be completed (the browser changed or it expired). Try again in the same browser.',
      provider: 'Sign-in with Google did not go through. Try again later.',
    },
    signedInAs: (email: string) => `Signed in: ${email}`,
    syncNow: 'Sync now',
    signOut: 'Sign out',
    signOutHint: 'Your list stays on the phone; only the backup stops.',
    status: {
      idle: (ago: string) => `Backed up · last sync ${ago}`,
      idleNever: 'Connected to the cloud.',
      syncing: 'Syncing…',
      offline: (n: number) => (n ? `Offline — ${n} ${n === 1 ? 'entry is' : 'entries are'} not backed up yet. Will sync when online.` : 'Offline — everything is backed up.'),
      error: (msg: string) => `Not synced: ${msg}`,
      unavailable: 'Cloud backup is unavailable right now. Your list is safe on this phone — it will sync when the cloud is back.',
      unavailablePending: (n: number) => `Cloud backup is unavailable right now. ${n} ${n === 1 ? 'entry is' : 'entries are'} waiting — all safe on this phone.`,
      authNeeded: 'Sign in again to keep backing up. Your list stays on the phone.',
      localOnly: 'Demo — not synced to the cloud.',
      unbound: 'This store is not connected to the cloud yet. Tap "Sync now".',
      pending: (n: number) => `${n} ${n === 1 ? 'entry' : 'entries'} not backed up yet`,
    },
    errors: {
      network: 'no connection',
      unavailable: 'the cloud is unavailable right now',
      auth: 'please sign in again',
      denied: 'the cloud refused (different account?)',
      store_gone: 'the store is no longer available in the cloud',
      server: 'cloud problem — will retry',
      unknown: 'something went wrong — will retry',
    },
    ago: { justNow: 'just now', minutes: (n: number) => `${n} min ago`, hours: (n: number) => `${n} ${n === 1 ? 'hour' : 'hours'} ago`, days: (n: number) => `${n} ${n === 1 ? 'day' : 'days'} ago` },
    skew: (min: number) => `Your phone’s clock looks wrong (≈ ${min} min off from the server). Fix it in the phone’s Settings so entries stay in the right order.`,
  },


  // ---------- P4/P5 (decided 2026-10-01) ----------
  tally: {
    title: 'Sales (tally)',
    hint: 'Tap a product for each sale. You do not have to tally every sale — it only helps the estimate.',
    count: (n: number) => (n === 1 ? '1 sale' : `${n} sales`),
    minus: 'remove one',
    save: 'Save',
    saved: (n: number) => `Recorded ${n} sales.`,
    unsavedQ: 'Some sales are not saved yet. Close anyway?',
  },

  ai: {
    signInFirst: 'Sign in first under More → Cloud backup to use the AI. Everything else still works.',
    errors: {
      signed_out: 'Sign in first under More → Cloud backup.',
      offline: 'No internet — the AI needs the internet. Everything else still works.',
      auth: 'Sign in again under More → Cloud backup.',
      rate_limited: 'Too many questions for now — try again later.',
      busy: 'The AI is busy right now — try again in a moment.',
      not_configured: 'The AI is not set up in this app yet.',
      too_large: 'The photo is too large — try a closer shot.',
      failed: 'Could not get an answer — try again.',
    },
  },

  scan: {
    title: 'Scan a receipt',
    textTitle: 'Write what happened',
    take: '📷 Take a photo',
    choose: '🖼️ Choose a photo',
    imageNote: 'The photo is not saved — it is only read, then discarded.',
    textHint: 'E.g. "bought 2 cases Coke 1560 at Puregold, 5 Kopiko left". You can also use the keyboard mic.',
    textPlaceholder: 'Write here…',
    mic: '🎤 Speak',
    listening: 'Listening…',
    read: 'Read',
    reading: 'Reading…',
    review: 'Check before saving',
    none: 'No items found.',
    unreadable: 'Could not read:',
    pick: 'Choose the product…',
    notInStore: (name: string) => `"${name}" — not in your products`,
    kindPurchase: 'Bought',
    kindCount: 'Left',
    qty: 'Qty',
    total: '₱ total',
    supplier: 'Supplier',
    when: 'When?',
    save: (n: number) => `Save (${n})`,
    saved: (n: number) => `Recorded ${n} entries.`,
    again: 'Start over',
  },

  ask: {
    title: 'Ask TindaBot',
    briefing: 'Today',
    placeholder: 'E.g. How many Coke are left? How much should I bring?',
    send: 'Ask',
    thinking: 'Looking…',
    unverified: 'not verified',
    unverifiedText: 'The answer has a number I could not verify — check it in the app.',
    looked: (what: string) => `Looked at: ${what}`,
    tools: { get_product: 'product', list_events: 'records', get_shopping_list: 'list', get_week_summary: 'report', get_customer: 'customer' },
    examples: ['What should I buy first?', 'How many are left of my best seller?', 'How much did I spend this week?'],
    note: 'Answers only from what you recorded. It never saves or changes anything.',
  },

  csv: {
    title: 'Import products (CSV)',
    hint: 'From a spreadsheet. Columns: name, category, unit_label, pack_size, pack_label, sell_price, natira. Existing products are not touched.',
    choose: 'Choose a CSV file',
    template: 'Download an example',
    noHeader: 'The file has no "name" column — see the example.',
    ready: (n: number) => (n === 1 ? '1 new product' : `${n} new products`),
    skipped: 'Left out:',
    exists: 'already a product',
    line: (n: number) => `Line ${n}`,
    errors: { no_name: 'no name', bad_pack_size: 'bad pack_size', bad_price: 'bad price', bad_natira: 'bad natira', duplicate: 'repeated in the file' },
    add: (n: number) => `Add (${n})`,
    added: (n: number) => `Added ${n} products.`,
    failed: 'Could not read the file.',
  },

  household: {
    title: 'Shared with',
    hint: 'Share the store with someone in your household. They use their own Google account and phone; both of you can record.',
    signInFirst: 'Sign in first to share or join.',
    demo: 'The demo cannot be shared.',
    invite: 'Make an invite code',
    code: 'Invite code',
    codeHint: (until: string) => `Give them the code. It works once, until ${until}.`,
    copy: 'Copy',
    copied: 'Code copied.',
    join: 'Join another store',
    joinPlaceholder: 'Invite code',
    joinBtn: 'Join',
    joined: (name: string) => `You now share ${name}.`,
    joinErrors: { invalid: 'Wrong, used or expired code.', too_many: 'Too many wrong codes — try again later.', own: 'That code is for your own store.' },
    members: 'Who has access',
    owner: 'owner',
    member: 'member',
    you: 'you',
    remove: 'Remove',
    removeQ: (who: string) => `Remove ${who}? They lose access; everything they recorded stays in the store.`,
    removed: 'Removed.',
    failed: 'That did not work — try again.',
    notReady: 'Sync the store to the cloud first.',
  },

  days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  daysLong: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
}

export const STRINGS: Record<Lang, Strings> = { tl: TL as Strings, en: EN }

/** Strings for a language — for non-React code and tests. Components use `useStrings()`. */
export function strings(lang: Lang): Strings {
  return STRINGS[lang]
}
